library(usethis)
library(devtools)
library(datarium)
library(ggplot2)
library(lmtest)
library(ie2misc)
library(Metrics)
library(car)

head(marketing)
tail(marketing)
nrow(marketing)
ncol(marketing)
str(marketing)
summary(marketing)

ggplot(data, aes(x = youtube, y = sales)) + geom_point() + stat_smooth(method = lm, color = "blue")
ggplot(data, aes(x = facebook, y = sales)) + geom_point() + stat_smooth(method = lm, color = "purple")
ggplot(data, aes(x = newspaper, y = sales)) + geom_point() + stat_smooth(method = lm, color = "red")

cor(marketing$sales, marketing$youtube)
cor(marketing$sales, marketing$facebook)
cor(marketing$sales, marketing$newspaper)


boxplot(marketing$youtube, col='red', xlab='Youtube')
boxplot(marketing$facebook, col='blue', xlab='Facebook')
boxplot(marketing$newspaper, col='green', xlab='Newspaper')
boxplot(marketing$sales, col='yellow', xlab='Sales')

set.seed(1234)
ind <- sample(2, nrow(marketing), replace = T, prob = c(0.8, 0.2))
print(ind)
head(ind)
tail(ind)
nrow(ind)
ncol(ind)
summary(ind)

train <- marketing[ind == 1,]
test <- marketing[ind == 2,]
head(train)
head(test)
tail(train)
tail(test)
nrow(train)
nrow(test)
ncol(train)
ncol(test)
summary(train)
summary(test)

cor(train$sales, train$youtube)
cor(train$sales, train$facebook)
cor(train$sales, train$newspaper)
cor(test$sales, test$youtube)
cor(test$sales, test$facebook)
cor(test$sales, test$newspaper)

#Model 1
model_youtube <- lm(sales~youtube, data = train)
summary(model_youtube)
coeff_youtube <- coefficients(model_youtube)
regl_youtube <- paste("Regression Line -> y: ", round(coeff_youtube[1], 4), " + ", round(coeff_youtube[2], 4), " * ", "youtube")
print(regl_youtube)
model_youtube_predict_train <- predict(model_youtube, train)
print(model_youtube_predict_train)
model_youtube_predict_test <- predict(model_youtube, test)
print(model_youtube_predict_test)
mae(train$sales,model_youtube_predict_train)
mae(test$sales,model_youtube_predict_test)
mse(train$sales,model_youtube_predict_train)
mse(test$sales,model_youtube_predict_test)
rmse(train$sales,model_youtube_predict_train)
rmse(test$sales,model_youtube_predict_test)
mape(train$sales,model_youtube_predict_train)
mape(test$sales,model_youtube_predict_test)
AIC(model_youtube)
BIC(model_youtube)

#Model 2
model_facebook <- lm(sales~facebook, data = train)
summary(model_facebook)
coeff_facebook <- coefficients(model_facebook)
regl_facebook <- paste("Regression Line -> y: ", round(coeff_facebook[1], 4), " + ", round(coeff_facebook[2], 4), " * ", "facebook")
print(regl_facebook)
model_facebook_predict_train <- predict(model_facebook, train)
print(model_facebook_predict_train)
model_facebook_predict_test <- predict(model_facebook, test)
print(model_facebook_predict_test)
mae(train$sales,model_facebook_predict_train)
mae(test$sales,model_facebook_predict_test)
mse(train$sales,model_facebook_predict_train)
mse(test$sales,model_facebook_predict_test)
rmse(train$sales,model_facebook_predict_train)
rmse(test$sales,model_facebook_predict_test)
mape(train$sales,model_facebook_predict_train)
mape(test$sales,model_facebook_predict_test)
AIC(model_facebook)
BIC(model_facebook)

#Model 3
model_newspaper <- lm(sales~newspaper, data = train)
summary(model_newspaper)
coeff_newspaper <- coefficients(model_newspaper)
regl_newspaper <- paste("Regression Line -> y: ", round(coeff_newspaper[1], 4), " + ", round(coeff_newspaper[2], 4), " * ", "newspaper")
print(regl_newspaper)
model_newspaper_predict_train <- predict(model_newspaper, train)
print(model_newspaper_predict_train)
model_newspaper_predict_test <- predict(model_newspaper, test)
print(model_newspaper_predict_test)
mae(train$sales,model_newspaper_predict_train)
mae(test$sales,model_newspaper_predict_test)
mse(train$sales,model_newspaper_predict_train)
mse(test$sales,model_newspaper_predict_test)
rmse(train$sales,model_newspaper_predict_train)
rmse(test$sales,model_newspaper_predict_test)
mape(train$sales,model_newspaper_predict_train)
mape(test$sales,model_newspaper_predict_test)
AIC(model_newspaper)
BIC(model_newspaper)

#Model 4
model_youtube_facebook <- lm(sales~youtube + facebook, data = train)
summary(model_youtube_facebook)
coeff_youtube <- coefficients(model_youtube_facebook)
regl_youtube_facebook <- paste("Regression Line -> y: ", round(coeff_youtube_facebook[1], 4), " + ", round(coeff_youtube_facebook[2], 4), " * ", "youtube_facebook")
print(regl_youtube_facebook)
model_youtube_facebook_predict_train <- predict(model_youtube_facebook, train)
print(model_youtube_facebook_predict_train)
model_youtube_facebook_predict_test <- predict(model_youtube_facebook, test)
print(model_youtube_facebook_predict_test)
mae(train$sales,model_youtube_facebook_predict_train)
mae(test$sales,model_youtube_facebook_predict_test)
mse(train$sales,model_youtube_facebook_predict_train)
mse(test$sales,model_youtube_facebook_predict_test)
rmse(train$sales,model_youtube_facebook_predict_train)
rmse(test$sales,model_youtube_facebook_predict_test)
mape(train$sales,model_youtube_facebook_predict_train)
mape(test$sales,model_youtube_facebook_predict_test)
AIC(model_youtube_facebook)
BIC(model_youtube_facebook)